version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  auth-service:
    build:
      context: .
      dockerfile: auth/Dockerfile.grpc
    ports:
      - "5001:5001"
    environment:
      - REDIS_HOST=your-redis-host
      - REDIS_PORT=your-redis-port

  geo-service:
    build:
      context: .
      dockerfile: geo/cmd/api/Dockerfile.grpc
    ports:
      - "50051:50051"
      - "8080:8080"
    depends_on:
      - prometheus
      - auth-service
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - RPC_PROTOCOL=json-rpc
